const municipiosNarino = [
  "Pasto",
  "Albán",
  "Aldana", 
  "Ancuyá",
  "Arboleda",
  "Barbacoas",
  "Belén",
  "Buesaco",
  "Colón",
  "Consacá",
  "Contadero",
  "Córdoba",
  "Cuaspud",
  "Cumbal",
  "Cumbitara",
  "Chachagüí",
  "El Charco",
  "El Peñol",
  "El Rosario",
  "El Tablón",
  "El Tambo",
  "Funes",
  "Guachucal",
  "Guaitarilla",
  "Gualmatán",
  "Iles",
  "Imués",
  "Ipiales",
  "La Cruz",
  "La Florida",
  "La Llanada",
  "La Tola",
  "La Unión",
  "Leiva",
  "Linares",
  "Los Andes",
  "Magüí",
  "Mallama",
  "Mosquera",
  "Nariño",
  "Olaya Herrera",
  "Ospina",
  "Francisco Pizarro",
  "Policarpa",
  "Potosí",
  "Providencia",
  "Puerres",
  "Pupiales",
  "Ricaurte",
  "Roberto Payán",
  "Samaniego",
  "San Bernardo",
  "San Lorenzo",
  "San Pablo",
  "San Pedro de Cartago",
  "Sandoná",
  "Santa Bárbara",
  "Santacruz",
  "Sapuyes",
  "Taminango",
  "Tangua",
  "San Andrés de Tumaco",
  "Túquerres",
  "Yacuanquer"
];

export default municipiosNarino